/*Creation Script for Address table*/
CREATE TABLE  "ADDRESS" 
   (	"ADDRESSID" NUMBER(7,0) NOT NULL ENABLE, 
	"ADDRESS_LINE1" VARCHAR2(50) NOT NULL ENABLE, 
	"ADDRESS_LINE2" VARCHAR2(50), 
	"CITY" VARCHAR2(20) NOT NULL ENABLE, 
	"POSTCODE" VARCHAR2(7) NOT NULL ENABLE, 
	"STATE" VARCHAR2(30) NOT NULL ENABLE, 
	"COUNTRY" VARCHAR2(30) NOT NULL ENABLE, 
	 CONSTRAINT "ADDRESS_PK" PRIMARY KEY ("ADDRESSID") ENABLE
   ) ;

CREATE OR REPLACE TRIGGER  "BI_ADDRESS" 
  before insert on "ADDRESS"               
  for each row  
begin   
  if :NEW."ADDRESSID" is null then 
    select "ADDRESS_SEQ".nextval into :NEW."ADDRESSID" from dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_ADDRESS" ENABLE;



/*Creation Script for CustomerData table*/

CREATE TABLE  "CUSTOMERDATA" 
   (	"CUSTOMERID" NUMBER(10,0) NOT NULL ENABLE, 
	"FIRSTNAME" VARCHAR2(30) NOT NULL ENABLE, 
	"LASTNAME" VARCHAR2(20), 
	"CONTACTNUMBER" NUMBER(10,0) NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(50) NOT NULL ENABLE, 
	"ADDRESSID" NUMBER(7,0) NOT NULL ENABLE, 
	 CONSTRAINT "CUSTOMERDATA_PK" PRIMARY KEY ("CUSTOMERID") ENABLE
   ) ;ALTER TABLE  "CUSTOMERDATA" ADD CONSTRAINT "CUSTOMERDATA_FK" FOREIGN KEY ("USERNAME")
	  REFERENCES  "LOGINDATA" ("USERNAME") ENABLE;ALTER TABLE  "CUSTOMERDATA" ADD CONSTRAINT "CUSTOMERDATA_FK_ADDRESS" FOREIGN KEY ("ADDRESSID")
	  REFERENCES  "ADDRESS" ("ADDRESSID") ENABLE;

CREATE OR REPLACE TRIGGER  "BI_CUSTOMERDATA" 
  before insert on "CUSTOMERDATA"               
  for each row  
begin   
  if :NEW."CUSTOMERID" is null then 
    select "CUSTOMERDATA_SEQ".nextval into :NEW."CUSTOMERID" from dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_CUSTOMERDATA" ENABLE;


/*Creation Script for LoginData table*/

CREATE TABLE  "LOGINDATA" 
   (	"USERNAME" VARCHAR2(50) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "LOGINDATA_PK" PRIMARY KEY ("USERNAME") ENABLE
   ) ;

CREATE OR REPLACE TRIGGER  "BI_LOGINDATA" 
  before insert on "LOGINDATA"               
  for each row  
begin   
  if :NEW."USERNAME" is null then 
    select "LOGINDATA_SEQ".nextval into :NEW."USERNAME" from dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_LOGINDATA" ENABLE;